# update-structure.ps1
# Generates STRUCTURE.md with current project file map
# Usage: .\update-structure.ps1

$root = $PSScriptRoot
$output = "$root\STRUCTURE.md"
$date = Get-Date -Format "yyyy-MM-dd HH:mm"

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# MarkPos - Structure")
$lines.Add("_Updated: $date_")
$lines.Add("_Generated by update-structure.ps1 - do not edit manually_")
$lines.Add("")

function Write-Tree {
    param(
        [string]$Path,
        [string]$Indent = "",
        [string[]]$Exclude = @("bin","obj",".git",".vs","node_modules","wwwroot\_framework")
    )

    $items = Get-ChildItem -Path $Path | Where-Object {
        $_.Name -notin $Exclude
    } | Sort-Object { -not $_.PSIsContainer }, Name

    foreach ($item in $items) {
        if ($item.PSIsContainer) {
            $lines.Add("$Indent[$($item.Name)/]")
            Write-Tree -Path $item.FullName -Indent "$Indent  " -Exclude $Exclude
        } else {
            $ext = $item.Extension.ToLower()
            if ($ext -in @(".cs",".razor",".csproj",".sln",".json",".md",".ps1",".sh",".sql",".http")) {
                $lines.Add("$Indent  $($item.Name)")
            }
        }
    }
}

$lines.Add("## src/")
$lines.Add('```')
Write-Tree -Path "$root\src"
$lines.Add('```')
$lines.Add("")

if (Test-Path "$root\tests") {
    $lines.Add("## tests/")
    $lines.Add('```')
    Write-Tree -Path "$root\tests"
    $lines.Add('```')
    $lines.Add("")
}

$lines.Add("## Projects (.csproj)")
$lines.Add("")
$projects = Get-ChildItem -Path "$root\src" -Recurse -Filter "*.csproj"
foreach ($proj in $projects | Sort-Object Name) {
    $relPath = $proj.FullName.Replace($root, "").TrimStart("\")
    $lines.Add("- ``$relPath``")
}

$lines | Set-Content -Path $output -Encoding UTF8
Write-Host "OK: STRUCTURE.md updated at $output"
